modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Wurmatron/Viral/issues"
[[mods]]
modId="viral"
version="0.0.1"
displayName="Viral"
updateJSONURL="https://raw.githubusercontent.com/Wurmatron/Viral/1.15/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/viral"
logoFile="logo.png"
credits=""
authors="Wurmatron, TryAngle"
description='''
'''